### ISSUE TITLE
Dragging elements that are placed directly on the Scene is unresponsive and slow

### ISSUE THREAD

**Issue by marvingrewe** [tudo-aqua/bgw#132]
This is not the case if the element is not directly on the Scene, e.g. if it is in a LinearLayout.

**Comment by fabiankluempers** [comment]
The cause for this is, that root components get removed from the scene, which triggers a complete rebuild of the scene. 

A WIP fix is on the performance-improvement branch. 
But now the dragged component disappears after an unsuccessful drag & drop gesture. 

If we get that fixed we can merge the performance-improvement into main.

**Comment by fabiankluempers** [comment]
The root cause for this problem is, that containers (Scenes, Containers, Layouts, UIComponents) rebuild all their children instead of only building newly added or deleting removed children. 

We should discard the approach on the performance-improvement branch and should focus on only building/rebuilding children where absolutely necessary.
