### ISSUE TITLE
Mismatching documentation for ComboBox

### ISSUE THREAD

**Issue by MonsterDruide1** [tudo-aqua/bgw#312]
**Are you refering to KDocs or GitHub Pages?**
Generated KDocs website (https://tudo-aqua.github.io/bgw/bgw-gui-kdoc/bgw-gui/tools.aqua.bgw.components.uicomponents/-check-box/index.html)

**In case of unclear documentation**
The parameters of constructor do not match the actual parameters to be specified in the BGW.

**Comment by dominikmaeckel** [comment]
Can you clearify what exactly is off with the documentation? Since the KDocs are generated they always match the code base.

https://tudo-aqua.github.io/bgw/bgw-gui-kdoc/bgw-gui/tools.aqua.bgw.components.uicomponents/-check-box/index.html
https://github.com/tudo-aqua/bgw/blob/main/bgw-gui/src/main/kotlin/tools/aqua/bgw/components/uicomponents/CheckBox.kt

**Comment by MonsterDruide1** [comment]
In the current version of BGW, the constructor looks like this:
```
public constructor ComboBox<T>(
    val posX: Number,
    val posY: Number,
    val width: Number,
    val height: Number,
    val font: Font,
    val prompt: String,
    val items: List<T>,
    val formatFunction: ((T) -> String)?
)
```

`prompt` and `items` are for example not represented in any way in the documentation.

**Comment by MonsterDruide1** [comment]
The links you mentioned point to `CheckBox`, I'm referring to `ComboBox`.

**Comment by dominikmaeckel** [comment]
I was refferring to CheckBox because your link pointed to it.

If you look closer into the documentation of ComboBox you will find that the constructor is actually defined as 

```
public constructor ComboBox<T>(
    posX: Number,
    posY: Number,
    width: Number,
    height: Number,
    font: Font,
    val prompt: String,
    items: List<T>,
    formatFunction: ((T) -> String)?
)
```

The constructor shown in the constructors tab is generated code by dokka and is only showing usage, not actual definition.

Dokka will put the documentation of parameters into the parameters tab but will put the documentation for `prompt` into the properties tab as it is defined as `val`. One can argue about this behaviour but this is what kdocs should look like.

**Comment by MonsterDruide1** [comment]
Okay, so I actually just confused those pages when looking through the documentation... Sorry, #NoIssue !
