### ISSUE TITLE
No initial window maximization

### ISSUE THREAD

**Issue by snaujokat** [tudo-aqua/bgw#89]
The application should not start maximized. However, just not setting `isMaximized = true` in `Frontend#startApplication` only partially does the trick, because then the original aspect ratio provided to the `BoardGameApplication` via width/height is lost. For me, this results in small black bars left and right of the window, but this surely depends on how many pixels the window decoration uses.

Side note: starting maximized (as it is currently implemented) and then un-maximizing it with the window decoration buttons produces a size without black borders. This is how the window should look after start.

**Comment by snaujokat** [comment]
Since the last update, initial window size is completely broken for me on both my Linux machines. For a short moment, a visible window appears that looks like 16:9, then it resizes to a thin line of one pixel width (plus window border) and a height that is a about 30% *more* than my actual screen size.

**Comment by dominikmaeckel** [comment]
intital window size is now 720p. Can be changed by setting width and height manually (also possible after start).
Auto resizing to layout bounds is currently not possible because Java cannot retrieve the titlebar height properly (6px offset on Windows, might be different on other devices.)
Please test under linux and close issue if solution is acceptable, otherwise comment.

**Comment by snaujokat** [comment]
I have minimal black borders when starting the application, but as this seems unfixable, it is fine for now. The completely broken behavior is gone.
